# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
dist: trusty
sudo: required

language: R
warnings_are_errors: false

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:marutter/c2d4u -y
  - sudo apt-get update -q
  - sudo apt-get install g++-4.9 -y
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 100

r_packages:
  - Rcpp
  - testthat
  - knitr
  - rmarkdown
  - covr

repos:
  CRAN: http://cran.rstudio.com

r:
  - release
  - devel

after_success:
  - Rscript -e 'covr::codecov(line_exclusions = "src/test.cpp")'
